# Settings for the spaceship theme.

# Prompt
SPACESHIP_CHAR_SYMBOL="$ "
SPACESHIP_CHAR_SYMBOL_ROOT="# "
SPACESHIP_CHAR_SYMBOL_SECONDARY="> "

# Docker
SPACESHIP_DOCKER_SYMBOL="docker "
# SPACESHIP_DOCKER_SYMBOL="\ue7b0 "

# Golang
SPACESHIP_GOLANG_SYMBOL="go "
# SPACESHIP_GOLANG_SYMBOL="\ue724 "

# Exit code
SPACESHIP_EXIT_CODE_SHOW="true"
SPACESHIP_EXIT_CODE_SYMBOL="!"
# SPACESHIP_EXIT_CODE_SYMBOL="\u00d7"

# Background jobs
SPACESHIP_JOBS_SYMBOL="\u231b"
